#! /bin/bash

INSTALL_PATH=.

start()
{
  #nohup python3 -u $INSTALL_PATH/MarketDataCollector.py TIME_SERIES_DAILY > log.txt 2>&1 & echo $! > pid.txt
  nohup python3 -u $INSTALL_PATH/MarketDataCollector.py TIME_SERIES_INTRADAY 60min > $INSTALL_PATH/log.txt 2>&1 & echo $! > $INSTALL_PATH/pid.txt
}

stop()
{
  cat $INSTALL_PATH/pid.txt | xargs kill
}

case $1 in
  start|stop) "$1" ;;
esac
