#! /bin/bash

INSTALL_PATH=/path/to/script/MarketDataCollector

start()
{
  nohup python3 -u $INSTALL_PATH/MarketDataCollector.py TIME_SERIES_DAILY > log.txt 2>&1 & echo $! > pid.txt
  #nohup python3 -u $INSTALL_PATH/MarketDataCollector.py TIME_SERIES_INTRADAY 60min > log.txt 2>&1 & echo $! > pid.txt
}

stop()
{
  cat pid.txt | xargs kill
}

case $1 in
  start|stop) "$1" ;;
esac
